- name: Fetch and run Docker image from Docker Hub
  hosts: localhost
  connection: local
  tasks:
    - name: Pull Docker image from Docker Hub
      docker_image:
        name: "sudhanshu1020/calculator-java-image:latest"
        source: pull

    - name: Run Docker container
      docker_container:
        name: calculator-container
        image: "sudhanshu1020/calculator-java-image:latest"
        state: started
        ports:
          - "8082:8082"