- name: Fetch and run Docker image from Docker Hub
  hosts: localhost
  connection: local
  tasks:
    - name: Pull Docker image from Docker Hub
      docker_image:
        name: "sudhanshu1020/calculator-java-image:latest"
        source: pull

    - name: Run Docker container
      command: docker run -dit -p 8082:8082 sudhanshu1020/calculator-java-image:latest
#      command: docker run -it sudhanshu1020/calculator-java-image:latest